syntax = "proto3";
package msg;

import "cs_attrib.proto";

// @desc 临时角色数据
message TmpCharacterData {
    uint64 inst_id = 1;                     // 角色唯一id
    uint32 tmp_character_id = 2;            // P_TmpCharacterTable 表格ID
    uint32 source = 3;                      // TmpCharacterSource 枚举
    repeated PBAttribDataElem attrib_data = 4;  // 角色属性数据
}

// @desc 拉取所有临时角色列表（全量，登录用）
// @cmd CS_TMP_CHARACTER_LIST_REQ
message CS_TmpCharacter_List_Req
{
}

// @desc 拉取所有临时角色列表 响应
// @cmd SC_TMP_CHARACTER_LIST_RSP
message SC_TmpCharacter_List_Rsp
{
    int32 result = 1;
    repeated TmpCharacterData list = 2;
}

// @desc 通知新增临时角色
// @cmd SC_TMP_CHARACTER_ADD_NTF
message SC_TmpCharacter_Add_Ntf
{
    repeated TmpCharacterData list = 1;
}

// @desc 通知删除临时角色
// @cmd SC_TMP_CHARACTER_DEL_NTF
message SC_TmpCharacter_Del_Ntf
{
    repeated uint64 list = 1;
}

// @desc 通知临时角色属性变更
// @cmd SC_TMP_CHARACTER_ATTR_CHANGED_NTF
message SC_TmpCharacter_Attr_Changed_Ntf
{
    repeated PBCharacterAttribData list = 1;
}
